<?php

namespace AppBundle\Repository;

use FOS\UserBundle\Model\User;

/**
 * BoardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProfessorBoards($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT b, p 
                     FROM AppBundle:Board b
                     JOIN b.project p
                     WHERE b.isFinalized = 0 
                     AND (b.evaluatorOne = :idUser
                     OR b.evaluatorTwo = :idUser
                     OR p.advisor = :idUser)')
            ->setParameter('idUser', $id);

        return $query->getResult();
    }

    public function getStudentBoards($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT b, p 
                     FROM AppBundle:Board b
                     JOIN b.project p
                     WHERE p.student = :idUser')
            ->setParameter('idUser', $id);

        return $query->getResult();
    }
}
