<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Busca todos os projetos que tiverem banca finalizada e nota acima de 9.
     */
    public function findByBoardFinalizedAndGrade()
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT b
                FROM AppBundle:Project p
                INNER JOIN AppBundle:Board b
                WHERE b.finalGrade > 9
                AND b.isFinalized = 1'
        );

//        var_dump($query->getResult());
//        die();
        return $query->getResult();
    }
}
