imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            path:  /home/u526102844/public_html/bibliotcc/logs/prod.log
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            #Heroku deploy
            path: 'php://stderr'
        console:
            type: console
            process_psr_3_messages: false
